# Generated by Django 3.2 on 2022-03-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_rename_date_timeseries_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
