# Generated by Django 3.2 on 2022-03-18 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_ticker_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='last_Refreshed',
        ),
        migrations.AddField(
            model_name='ticker',
            name='last_Refreshed_1D',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ticker',
            name='last_Refreshed_30m',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ticker',
            name='last_Refreshed_60m',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
