# Generated by Django 3.2 on 2022-03-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='margen',
            field=models.IntegerField(choices=[(1, '1:1'), (2, '2:1'), (3, '3:1'), (4, '4:1'), (5, '5:1')], default=0),
            preserve_default=False,
        ),
    ]
